elasticsearch:
  uris: http://localhost:9200
  username: elastic
  password: elastic

keycloak:
  realm: codeflix
  host: http://localhost:18080

server:
  port: 8080
  undertow:
    threads:
      worker: 10
      io: 2