elasticsearch:
  uris: http://localhost:9200
  username: elastic
  password: elastic

graphql:
  graphiql: true

keycloak:
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  host: http://localhost:8443
  realm: codeflix

rest-client:
  keycloak:
    read-timeout: 1_000

server:
  undertow:
    threads:
      worker: 10
      io: 2

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration