version: '3.9'

services:
  zookeeper-catalogo-de-videos:
    container_name: zookeeper-catalogo-de-videos
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-catalogo-de-videos
    healthcheck:
      test: [ "CMD", "zookeeper-shell", "localhost:2181", "ls", "/" ]
      interval: 10s
      timeout: 5s
      retries: 3

  kafka-catalogo-de-videos:
    container_name: kafka-catalogo-de-videos
    image: confluentinc/cp-kafka:latest
    depends_on:
      zookeeper-catalogo-de-videos:
        condition: service_healthy
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-catalogo-de-videos:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-catalogo-de-videos:9092,OUTSIDE://host.docker.internal:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - kafka-catalogo-de-videos
    volumes:
      - kafka-catalogo-de-videos:/var/lib/kafka/data
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9092" ]
      interval: 10s
      timeout: 5s
      retries: 3

  control-center-catalogo-de-videos:
    container_name: control-center-catalogo-de-videos
    image: confluentinc/cp-enterprise-control-center:6.0.1
    hostname: control-center
    depends_on:
      kafka-catalogo-de-videos:
        condition: service_healthy
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: kafka-catalogo-de-videos:9092
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_CONNECT_CLUSTER: http://kafka-connect-catalogo-de-videos:8083
      PORT: 9021
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - kafka-catalogo-de-videos
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9021" ]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  kafka-catalogo-de-videos:
    external: true

volumes:
  kafka-catalogo-de-videos:
    external: true