name: Auto Open PR for Feature Branch

on:
  push:
    branches:
      - 'feature*'

jobs:
  open_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Auto Open PR for Feature Branch'
          branch: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
